# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout leet-chem repository
      uses: actions/checkout@v3
    
    - name: Checkout openchemlib-hyperspace repository
      uses: actions/checkout@v3
      with:
        repository: Actelion/openchemlib-hyperspace
        ref: v2.2.2    
              
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build openchemlib-hyperspace with Maven
      working-directory: openchemlib-hyperspace
      run: mvn -B clean install
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./leet
